# Introduction
Numpy --> *Num*erical *Py*thon


## Import Numpy

In [2]:
import numpy as np

## Numpy Array


In [6]:
my_list = [1,2,3,4,5]
arr = np.array(my_list)
print(arr*2)
print(arr>2)
print (arr[arr>2])  # Filtering
print(arr[0:3])  # Slicing

[ 2  4  6  8 10]
[False False  True  True  True]
[3 4 5]
[1 2 3]


In [ ]:
my_list1 = [1,2,3,4]
my_list1 = my_list1 * 2 
print(my_list1) # List repetition

[1, 2, 3, 4, 1, 2, 3, 4]


In [15]:
array = np.array([['A','B','C'], ['D','E','F']])
print(array.ndim) # Number of dimensions
print(array.shape) # Shape of the array
print(array[0,2]) # Accessing elements

2
(2, 3)
C


In [16]:
word = array[0,1] + array[1,1] + array[1,1]
print(word) # Concatenation

BEE


In [ ]:
array = np.array([[1,2,3,4], 
                  [5,6,7,8], 
                  [9,10,11,12], 
                  [13,14,15,16]])

# array[start:end:step]
print(array[0:4:2]) # Slicing 2D array
print(array[::-1]) # Reversing the array
print(array[:,1]) # Accessing 2nd column
print(array[1:3,1:3]) # Slicing sub-array

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[ 2  6 10 14]
[[ 6  7]
 [10 11]]


In [ ]:
array = np.array([1,2,3]) #Scalar Arithmetic operations
print(array + 1) 
print(array - 2)
print(array * 3)
print(array / 4)
print(array ** 5)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [12]:
array = np.array([1.011,2.5,3.99]) # Vectorized operations
print(np.sqrt(array))
print(np.round(array))
print(np.pi)

[1.00548496 1.58113883 1.99749844]
[1. 2. 4.]
3.141592653589793


In [ ]:
radii = np.array([1,2,3])
print(np.pi * (radii**2)) # Area of circles with given radii

[ 3.14159265 12.56637061 28.27433388]


In [15]:
array1 = np.array([1,2,3]) # Element-wise operations
array2 = np.array([4,5,6])
print(array1 + array2) 
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [3]:
scores = np.array([48,82,100,63,35]) # Comparison Operators
print(scores == 100)
print(scores >= 50)
scores[scores < 60] = 0 # Failing scores set to 0
print(scores)

[False False  True False False]
[False  True  True  True False]
[  0  82 100  63   0]


In [ ]:
array1 = np.array([[1,2,3,4]])
array2 = np.array([[1],[2],[3],[4]])
print(array1.shape)
print(array2.shape)

print(array1*array2) # Broadcasting

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [ ]:
array1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
array2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(array1.shape)
print(array2.shape)
print(array1*array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [14]:
array = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])

print(np.sum(array))
print(np.mean(array)) # Aggregate functions
print(np.std(array)) # Aggregate functions
print(np.var(array)) # Aggregate functions
print(np.max(array)) # Aggregate functions
print(np.min(array)) # Aggregate functions
print(np.argmin(array)) # Aggregate functions
print(np.argmax(array)) # Aggregate functions

print(np.sum(array, axis=0))
print(np.sum(array, axis=1))

55
5.5
2.8722813232690143
8.25
10
1
0
9
[ 7  9 11 13 15]
[15 40]


In [ ]:
ages = np.array([[21,17,19,20,16,30,18,65],
                 [39,22,15,99,18,19,20,21]])

teenagers = ages[ages < 18]
adults = ages[(ages >= 18) & (ages < 65)]
seniors = ages[ages >=65 ]
evens = ages[ages % 2 == 0] 
odds = ages[ages % 2 != 0]

print(teenagers) # Filtering with multiple conditions
print(adults)
print(seniors)
print(evens)
print(odds)

[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[65 99]
[20 16 30 18 22 18 20]
[21 17 19 65 39 15 99 19 21]


In [ ]:
rng = np.random.default_rng() # Random number generation
np.random.seed(seed=1) 
print(rng.integers(low=1, high=101, size=5)) # Single dimensional array
print(rng.integers(low=1, high=101, size=(2,3))) # Multi-dimensional array

[25 48 53 40 95]
[[10 91 58]
 [30 31 99]]


In [94]:
np.random.seed(seed=1) 
print(np.random.uniform(low=-1, high=1, size=(3,2))) # Random floats in a given range

[[-0.16595599  0.44064899]
 [-0.99977125 -0.39533485]
 [-0.70648822 -0.81532281]]


In [95]:
rng = np.random.default_rng()
array = np.array([1,2,3,4,5])
rng.shuffle(array) # Shuffling an array
print(array)

[4 2 1 3 5]


In [7]:
rng = np.random.default_rng()
emojis = np.array(['😀','😂','😍','😎','🤩','😡','😭','👍','🙏','💪'])
# creating a 2d array of random emojis
emojis = rng.choice(emojis, size=(2,5), replace=False) 
print(emojis)

[['💪' '😎' '😀' '🤩' '😡']
 ['😂' '👍' '😍' '😭' '🙏']]
